### PR TITLE
Feat/global data updater

### PR DESCRIPTION
**Pull request by JonKrone**

### CODE REVIEW

**Comment by dotkam** [comment]
That covers a lot.  Interesting use of fetch.  Overall, way ahead of my implementation level (checking if task already exists, etc).  There are a lot of moving pieces (global, list, item). Global sets up props variables.  Per my understanding, it's typical to put ajax requests in 'componentDidMount' lifecycle event.  Function over form though for an MVP -- plus I don't exactly know what I'm talking about!

woah, I can edit your comments!

**Comment by JonKrone** [comment]
There are a lot of moving pieces and not every part of this is react's style. I think a good portion of the next steps are to refactor it to be more clear and in line with react best practices and style guides. How can I help clarify the chain of events and how state is managed / view is updated? Would it help if I wrote a summary or commented more?

**Comment by ghost** [comment]
Reviewing for merge

Definitely comment more for everyone to understand, you're already doing a good job of it, 
and reference other files if they're connected

**Comment by ghost** [comment]
all right, looks good

**Pull request merged**
